### ISSUE TITLE
Button don't works

### ISSUE THREAD

**Issue by demidko** [digitalocean/sample-dockerfile#10]
_The repo you are trying to deploy does not contain a .do/deploy.template.yaml file. If you are the owner of the repo, please add an app spec in order to enable usage of our third-party app deployment feature. If you are not the owner, you must fork this repo to your own GitHub account in order to deploy it._

<img width="1024" alt="image" src="https://user-images.githubusercontent.com/26452002/113480582-4ff16900-94d8-11eb-991b-c29059fa31b2.png">

**Comment by kamaln7** [comment]
Hi @demidko,

I was unable to reproduce this. Can you please try again in case it was a temporary error?

If it still doesn't work, please try both of these links and let me know if any of them works.

1. https://cloud.digitalocean.com/apps/new?repo=https://github.com/digitalocean/sample-python/tree/main
2. https://cloud.digitalocean.com/apps/new?repo=https://github.com/kamaln7/slack-emoji-papertrail/tree/main

Thanks!

**Comment by demidko** [comment]
> I was unable to reproduce this. Can you please try again in case it was a temporary error?

I think I understand what's the matter. Everything worked after paying off the debt for the previous month. But the error message really wrong.

**Comment by kamaln7** [comment]
Thanks for the update @demidko. Glad to hear it's working now.

**Comment by pirate** [comment]
I 2nd that this error message is confusing, it shows up even when there is clearly a file in the right location.

It should have more detail as to why the file is failing if a file does exist.
