### ISSUE TITLE
Not nearly enough detail in this example

### ISSUE THREAD

**Issue by pirate** [digitalocean/sample-dockerfile#11]
- how do you attach volumes?
- how do you specify the source dir the docker build should take place in?
- how do you specify a remote image on docker hub instead of building it from scratch on every deploy?
- how do you specify the entrypoint and command?
- how do you specify the port**s** to expose to the outside world? (especially if there are multiple ports)

Some of these things are alluded to in the docs, but this example repo has none of them, making users just have to figure it out via trial and error, which gets frustrating fast.

**Comment by kamaln7** [comment]
Hi @pirate,

This is very helpful feedback, thank you. I've shared this with the team and we'll update the docs to be clearer about these points. Meanwhile, I'll try to briefly answer them for you. Let me know if you have any additional questions.

> * how do you attach volumes?

Volumes are not supported at this time. You can use Spaces for storage but your app will need to know how to use an object store for files as it cannot be mounted as a filesystem directory.

> * how do you specify the source dir the docker build should take place in?

We're working on adding this option to the UI, but you can do that in the app spec. In the Settings tab, you can download your app spec, edit it, and upload the new version. Alternatively, you can use [doctl](https://www.digitalocean.com/docs/apis-clis/doctl/how-to/install/) to retrieve the spec (`doctl apps list` and `doctl apps spec get <app-id>`) and upload the new version (`doctl apps update --spec spec.yaml <app id>`).

```yaml
name: app
services:
  - name: example
    dockerfile_path: Dockerfile
    source_dir: api
```

Both `dockerfile_path` and `source_dir` are relative to the repository root.

See [Reference for App Specification](https://docs.digitalocean.com/products/app-platform/references/app-specification-reference/) for more info.

> * how do you specify a remote image on docker hub instead of building it from scratch on every deploy?
> * how do you specify the entrypoint and command?
> * how do you specify the port**s** to expose to the outside world? (especially if there are multiple ports)

**Comment by pirate** [comment]
> Volumes are not supported at this time

Ah thats unfortunate, that rules out my use case (and I'd guess the majority of off-the-shelf docker containers). I'll give it another try when Volumes are supported.

**Comment by kamaln7** [comment]
@pirate Sorry, I hit enter too soon. Volumes are definitely on the roadmap but I don't have an ETA that I can share. Would you mind expanding more on your usecase? That would help us prioritize this feature.

**Comment by pirate** [comment]
I'm trying to offer a 1-click deploy to ArchiveBox users: https://github.com/ArchiveBox/ArchiveBox

Here are my attempts at getting it working so far:

- https://github.com/ArchiveBox/ArchiveBox/commit/f473114e34e12970d24aab17277f569658f7f66c
- https://github.com/ArchiveBox/ArchiveBox/commit/9999721659f9d8a151720c00953cb61d7853a214
- https://github.com/ArchiveBox/ArchiveBox/commit/985740b0fb753542a483ac0ed630df59c2cbebd4
- https://github.com/ArchiveBox/ArchiveBox/commit/145dda3e0fd7a88da9dededb882c3654676aad22

All I want is this `image: archivebox/archivebox:latest` deployed to a DO droplet, with `/data` mounted as a volume, and port `8000` exposed to the internet.

It's a fairly standard linuxserver.io-style Docker image, it uses SQLite and the filesystem heavily for state though, so needs a writable filesystem, which doesn't seem to be supported even without a volume:

![image](https://user-images.githubusercontent.com/511499/116748509-92ba3a00-a9cd-11eb-9573-c329c8bfdbc2.png)

**Comment by kamaln7** [comment]
Thanks for the info @pirate. That makes sense. As for the SQLite error, that's something we're aware of and have a fix for on the way, but even with that working, the filesystem will still be ephemeral and so you wouldn't be able to run ArchiveBox properly. Also, cool project :)

**Comment by pirate** [comment]
I could live with ephemeral, it's not ideal but I'd just rsync it to s3 or something every few seconds.
