### ISSUE TITLE
Can you add comments to the Dockerfile?

### ISSUE THREAD

**Issue by fonsp** [digitalocean/sample-dockerfile#6]
It's difficult to understand how I can make this work for my own build scripts.

**Comment by fonsp** [comment]
Specifically: how do I access my repository's files from the container? What does `COPY . .` do?

**Comment by kamaln7** [comment]
Hi @fonsp 

Thanks for suggestion! We'll update the Dockerfile.

In the build environment, your repo is cloned and then it is built using the specified Dockerfile. The build context is set to the root of your repository, so `COPY . /app` would copy everything in your repo to the `/app` directory inside the container image. `COPY . .` would copy them to the working directory in the container. By default the working directory is set to `/` and it can be changed using the `WORKDIR /app` directive.

If you need to you can change the build context that the Dockerfile build is run in by setting the `source_dir` directory relative to the repo root. For more info please see the [App Specification Reference](https://www.digitalocean.com/docs/app-platform/references/app-specification-reference/).
