### ISSUE TITLE
Apps Plataform accepet Docker-Compose?

### ISSUE THREAD

**Issue by LucasViniciusPereira** [digitalocean/sample-dockerfile#8]
My project uses docker, but it is a microservice, so i need to use docker-compose, can i use the platform app for that?

**Comment by kamaln7** [comment]
Hi @LucasViniciusPereira,

App Platform does not directly support docker-compose, but apps can have multiple components. So you can create a component for each of your docker-compose services.

Components within the same app will be able to access each other through the internal network if that is something that you need. For more information on component-to-component access, please see this page: https://www.digitalocean.com/community/questions/app-platform-component-to-component-requests

**Comment by pirate** [comment]
Is there any hope of supporting docker compose specs in the future? It's a common standard and would avoid a lot of duplication (having to redefine services all the services in two yaml files).
